[project]
name = "python"
version = "0.1.0"
description = "Python for Machine Learning"
authors = ["Jim Hargrave <jim.hargrave@strakergroup.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.9.*"
numpy = "*"
pandas = "*"
scikit-learn = "*"
matplotlib = "*"
JAX = "*"
tensorflow-gpu = "*"
jupyter = "*"
pytorch-gpu = "*"
keras = "*"

[target.unix.dependencies]
pixi-pycharm = "*"
