[project]
name = "python"
version = "0.1.0"
description = "Python for Machine Learning"
authors = ["Jim Hargrave <jim.hargrave@strakergroup.com>"]
channels = ["conda-forge", "nvidia", "pytorch"]
platforms = ["linux-64"]

[dependencies]
cudnn = "*"
cuda = "*"
python = ">=3.10"
jax = "*"
jaxlib = "* *cuda*"
numpy = "*"
pandas = "*"
scikit-learn = "*"
matplotlib = "*"
jupyter = "*"
keras = "*"
pytest = "*"
ipython = "*"
coloredlogs = "*"
pylint = "*"

[target.unix.dependencies]
pixi-pycharm = "*"

[system-requirements]
cuda = "12"