[project]
name = "python"
version = "1.0.0"
description = "Python for Machine Learning"
authors = ["Jim Hargrave <jim.hargrave@strakergroup.com>"]
channels = ["conda-forge", "nvidia"]
platforms = ["linux-64"]

[dependencies]
pip = "*"
pydantic = "*"
python = "~=3.11"
numpy = "*"
pandas = "*"
scikit-learn = "*"
matplotlib = "*"
jupyter = "*"
pytest = "*"
ipython = "*"
coloredlogs = "*"
pylint = "*"
python-dotenv = "*"
llama-cpp-python = "*"

[pypi-dependencies]
torch = "*"
dspy-ai = { git = "https://github.com/stanfordnlp/dspy.git", extras = ["chromadb"]}
textgrad = { git = "https://github.com/zou-group/textgrad.git" }

[[tool.pixi.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu124"
packages = ["torch"]

[system-requirements]
cuda = "12.4"
