[project]
name = "python"
version = "0.1.0"
description = "Python for Machine Learning"
authors = ["Jim Hargrave <jim.hargrave@strakergroup.com>"]
channels = ["conda-forge", "nvidia"]
platforms = ["linux-64"]

[dependencies]
cudnn = "*"
cuda = ">=12"
cuda-nvcc = { channel = "nvidia", version = "*" }
python = "~=3.12"
jaxlib = "*=*cuda*"
jax = "*"
numpy = "*"
pandas = "*"
scikit-learn = "*"
matplotlib = "*"
jupyter = "*"
keras = "*"
pytest = "*"
ipython = "*"
coloredlogs = "*"
pylint = "*"
python-dotenv = "*"
llama-cpp-python = "*"
openai = "*"

[pypi-dependencies]
torch = "*"
google-generativeai = "*"

[[tool.pixi.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu121"
packages = ["torch"]

[target.unix.dependencies]
pixi-pycharm = "*"

[system-requirements]
cuda = "12"
