[project]
name = "python"
version = "0.1.0"
description = "Python for Machine Learning"
authors = ["Jim Hargrave <jim.hargrave@strakergroup.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.11.*"
numpy = "1.21.*"
pandas = "1.3.*"
scikit-learn = "1.0.*"
matplotlib = "3.4.*"
jupyter = "1.0.*"
