[project]
name = "python"
version = "0.1.0"
description = "Python for Machine Learning"
authors = ["Jim Hargrave <jim.hargrave@strakergroup.com>"]
channels = ["conda-forge", "nvidia"]
platforms = ["linux-64"]

[dependencies]
pip = "*"
python = "~=3.12"
jaxlib = "*=*cuda*"
jax = "*"
numpy = "*"
pandas = "*"
scikit-learn = "*"
matplotlib = "*"
jupyter = "*"
keras = "*"
pytest = "*"
ipython = "*"
coloredlogs = "*"
pylint = "*"
python-dotenv = "*"
llama-cpp-python = "*"
openai = "*"
ollama = "*"
sentencepiece = ">=0.1.96,<0.2.0"

[pypi-dependencies]
torch = "*"
google-generativeai = "*"
guidance = "*"
tokenizers = "*"
unbabel-comet = "*"

[[tool.pixi.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu123"
packages = ["torch"]

[target.unix.dependencies]
pixi-pycharm = "*"

[system-requirements]
cuda = "12.3"



