[project]
name = "python"
version = "0.1.0"
description = "Python for Machine Learning"
authors = ["Jim Hargrave <jim.hargrave@strakergroup.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.11.*"
numpy = "*"
pandas = "*"
scikit-learn = "*"
matplotlib = "*"
JAX = "*"
jupyter = ">=1.0.0,<1.1"
tensorflow = "*"
pytorch = ">=2.1.2,<2.2"
keras = ">=2.15.0,<2.16"

[target.unix.dependencies]
pixi-pycharm = "*"
