[project]
name = "python"
version = "1.0.0"
description = "Python for Machine Learning"
authors = ["Jim Hargrave <jim.hargrave@strakergroup.com>"]
channels = ["conda-forge", "nvidia"]
platforms = ["linux-64"]

[dependencies]
pip = "*"
python = "~=3.11"
numpy = "*"
pandas = "*"
scikit-learn = "*"
matplotlib = "*"
jupyter = "*"
pytest = "*"
ipython = "*"
coloredlogs = "*"
pylint = "*"
python-dotenv = "*"
dspy-ai = "*"

[pypi-dependencies]
torch = "*"

[[tool.pixi.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu124"
packages = ["torch"]

[target.unix.dependencies]
pixi-pycharm = "*"

[system-requirements]
cuda = "12.4"



